name: Build

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        runner: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
      - name: Build debug
        run: |
          cargo build --all-features
      - name: Build release
        run: |
          cargo build --release --all-features
